/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ApplicationUnhealthyEvaluations : List of health evaluations that resulted in the current aggregated health state.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApplicationUnhealthyEvaluations {}

impl Default for ApplicationUnhealthyEvaluations {
    fn default() -> Self {
        Self::new()
    }
}

impl ApplicationUnhealthyEvaluations {
    /// List of health evaluations that resulted in the current aggregated health state.
    pub fn new() -> ApplicationUnhealthyEvaluations {
        ApplicationUnhealthyEvaluations {}
    }
}
