/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ApplicationScopedVolumeCreationParameters : Describes parameters for creating application-scoped volumes.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApplicationScopedVolumeCreationParameters {
    /// Specifies the application-scoped volume kind.
    #[serde(rename = "kind")]
    kind: ::models::ApplicationScopedVolumeKind,
    /// User readable description of the volume.
    #[serde(rename = "description")]
    description: Option<String>,
}

impl ApplicationScopedVolumeCreationParameters {
    /// Describes parameters for creating application-scoped volumes.
    pub fn new(
        kind: ::models::ApplicationScopedVolumeKind,
    ) -> ApplicationScopedVolumeCreationParameters {
        ApplicationScopedVolumeCreationParameters {
            kind,
            description: None,
        }
    }

    pub fn set_kind(&mut self, kind: ::models::ApplicationScopedVolumeKind) {
        self.kind = kind;
    }

    pub fn with_kind(
        mut self,
        kind: ::models::ApplicationScopedVolumeKind,
    ) -> ApplicationScopedVolumeCreationParameters {
        self.kind = kind;
        self
    }

    pub fn kind(&self) -> &::models::ApplicationScopedVolumeKind {
        &self.kind
    }

    pub fn set_description(&mut self, description: String) {
        self.description = Some(description);
    }

    pub fn with_description(
        mut self,
        description: String,
    ) -> ApplicationScopedVolumeCreationParameters {
        self.description = Some(description);
        self
    }

    pub fn description(&self) -> Option<&String> {
        self.description.as_ref()
    }

    pub fn reset_description(&mut self) {
        self.description = None;
    }
}
