/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 6.5.0.36
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ApplicationTypeStatus : The status of the application type.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApplicationTypeStatus {}

impl Default for ApplicationTypeStatus {
    fn default() -> Self {
        Self::new()
    }
}

impl ApplicationTypeStatus {
    /// The status of the application type.
    pub fn new() -> ApplicationTypeStatus {
        ApplicationTypeStatus {}
    }
}

// TODO enum
// List of ApplicationTypeStatus
//const (
//
//
//
//)
