/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 7.2.0.46
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// AutoScalingMechanismKind : Enumerates the mechanisms for auto scaling.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AutoScalingMechanismKind {}

impl Default for AutoScalingMechanismKind {
    fn default() -> Self {
        Self::new()
    }
}

impl AutoScalingMechanismKind {
    /// Enumerates the mechanisms for auto scaling.
    pub fn new() -> AutoScalingMechanismKind {
        AutoScalingMechanismKind {}
    }
}

// TODO enum
// List of AutoScalingMechanismKind
//const (
//
//
//
//)
