/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ClusterHealth : Represents the health of the cluster. Contains the cluster aggregated health state, the cluster application and node health states as well as the health events and the unhealthy evaluations.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ClusterHealth {
    /// The HealthState representing the aggregated health state of the entity computed by Health Manager. The health evaluation of the entity reflects all events reported on the entity and its children (if any). The aggregation is done by applying the desired health policy.
    #[serde(rename = "AggregatedHealthState")]
    aggregated_health_state: Option<::models::HealthState>,
    /// The list of health events reported on the entity.
    #[serde(rename = "HealthEvents")]
    health_events: Option<Vec<::models::HealthEvent>>,
    /// The unhealthy evaluations that show why the current aggregated health state was returned by Health Manager.
    #[serde(rename = "UnhealthyEvaluations")]
    unhealthy_evaluations: Option<::models::UnhealthyEvaluations>,
    /// Shows the health statistics for all children types of the queried entity.
    #[serde(rename = "HealthStatistics")]
    health_statistics: Option<::models::HealthStatistics>,
    /// Cluster node health states as found in the health store.
    #[serde(rename = "NodeHealthStates")]
    node_health_states: Option<Vec<::models::NodeHealthState>>,
    /// Cluster application health states as found in the health store.
    #[serde(rename = "ApplicationHealthStates")]
    application_health_states: Option<Vec<::models::ApplicationHealthState>>,
}

impl Default for ClusterHealth {
    fn default() -> Self {
        Self::new()
    }
}

impl ClusterHealth {
    /// Represents the health of the cluster. Contains the cluster aggregated health state, the cluster application and node health states as well as the health events and the unhealthy evaluations.
    pub fn new() -> ClusterHealth {
        ClusterHealth {
            aggregated_health_state: None,
            health_events: None,
            unhealthy_evaluations: None,
            health_statistics: None,
            node_health_states: None,
            application_health_states: None,
        }
    }

    pub fn set_aggregated_health_state(
        &mut self,
        aggregated_health_state: ::models::HealthState,
    ) {
        self.aggregated_health_state = Some(aggregated_health_state);
    }

    pub fn with_aggregated_health_state(
        mut self,
        aggregated_health_state: ::models::HealthState,
    ) -> ClusterHealth {
        self.aggregated_health_state = Some(aggregated_health_state);
        self
    }

    pub fn aggregated_health_state(&self) -> Option<&::models::HealthState> {
        self.aggregated_health_state.as_ref()
    }

    pub fn reset_aggregated_health_state(&mut self) {
        self.aggregated_health_state = None;
    }

    pub fn set_health_events(
        &mut self,
        health_events: Vec<::models::HealthEvent>,
    ) {
        self.health_events = Some(health_events);
    }

    pub fn with_health_events(
        mut self,
        health_events: Vec<::models::HealthEvent>,
    ) -> ClusterHealth {
        self.health_events = Some(health_events);
        self
    }

    pub fn health_events(&self) -> Option<&Vec<::models::HealthEvent>> {
        self.health_events.as_ref()
    }

    pub fn reset_health_events(&mut self) {
        self.health_events = None;
    }

    pub fn set_unhealthy_evaluations(
        &mut self,
        unhealthy_evaluations: ::models::UnhealthyEvaluations,
    ) {
        self.unhealthy_evaluations = Some(unhealthy_evaluations);
    }

    pub fn with_unhealthy_evaluations(
        mut self,
        unhealthy_evaluations: ::models::UnhealthyEvaluations,
    ) -> ClusterHealth {
        self.unhealthy_evaluations = Some(unhealthy_evaluations);
        self
    }

    pub fn unhealthy_evaluations(
        &self,
    ) -> Option<&::models::UnhealthyEvaluations> {
        self.unhealthy_evaluations.as_ref()
    }

    pub fn reset_unhealthy_evaluations(&mut self) {
        self.unhealthy_evaluations = None;
    }

    pub fn set_health_statistics(
        &mut self,
        health_statistics: ::models::HealthStatistics,
    ) {
        self.health_statistics = Some(health_statistics);
    }

    pub fn with_health_statistics(
        mut self,
        health_statistics: ::models::HealthStatistics,
    ) -> ClusterHealth {
        self.health_statistics = Some(health_statistics);
        self
    }

    pub fn health_statistics(&self) -> Option<&::models::HealthStatistics> {
        self.health_statistics.as_ref()
    }

    pub fn reset_health_statistics(&mut self) {
        self.health_statistics = None;
    }

    pub fn set_node_health_states(
        &mut self,
        node_health_states: Vec<::models::NodeHealthState>,
    ) {
        self.node_health_states = Some(node_health_states);
    }

    pub fn with_node_health_states(
        mut self,
        node_health_states: Vec<::models::NodeHealthState>,
    ) -> ClusterHealth {
        self.node_health_states = Some(node_health_states);
        self
    }

    pub fn node_health_states(
        &self,
    ) -> Option<&Vec<::models::NodeHealthState>> {
        self.node_health_states.as_ref()
    }

    pub fn reset_node_health_states(&mut self) {
        self.node_health_states = None;
    }

    pub fn set_application_health_states(
        &mut self,
        application_health_states: Vec<::models::ApplicationHealthState>,
    ) {
        self.application_health_states = Some(application_health_states);
    }

    pub fn with_application_health_states(
        mut self,
        application_health_states: Vec<::models::ApplicationHealthState>,
    ) -> ClusterHealth {
        self.application_health_states = Some(application_health_states);
        self
    }

    pub fn application_health_states(
        &self,
    ) -> Option<&Vec<::models::ApplicationHealthState>> {
        self.application_health_states.as_ref()
    }

    pub fn reset_application_health_states(&mut self) {
        self.application_health_states = None;
    }
}
