/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 7.2.0.46
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DeployedServiceReplicaInfoList : List of deployed service replica information.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeployedServiceReplicaInfoList {}

impl Default for DeployedServiceReplicaInfoList {
    fn default() -> Self {
        Self::new()
    }
}

impl DeployedServiceReplicaInfoList {
    /// List of deployed service replica information.
    pub fn new() -> DeployedServiceReplicaInfoList {
        DeployedServiceReplicaInfoList {}
    }
}
