/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ManagedIdentityAzureBlobBackupStorageDescription : Describes the parameters for Azure blob store (connected using managed identity) used for storing and enumerating backups.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ManagedIdentityAzureBlobBackupStorageDescription {
    /// The kind of backup storage, where backups are saved.
    #[serde(rename = "StorageKind")]
    storage_kind: ::models::BackupStorageKind,
    /// Friendly name for this backup storage.
    #[serde(rename = "FriendlyName")]
    friendly_name: Option<String>,
    /// The type of managed identity to be used to connect to Azure Blob Store via Managed Identity.
    #[serde(rename = "ManagedIdentityType")]
    managed_identity_type: ::models::ManagedIdentityType,
    /// The Blob Service Uri to connect to the Azure blob store..
    #[serde(rename = "BlobServiceUri")]
    blob_service_uri: String,
    /// The name of the container in the blob store to store and enumerate backups from.
    #[serde(rename = "ContainerName")]
    container_name: String,
}

impl ManagedIdentityAzureBlobBackupStorageDescription {
    /// Describes the parameters for Azure blob store (connected using managed identity) used for storing and enumerating backups.
    pub fn new(
        storage_kind: ::models::BackupStorageKind,
        managed_identity_type: ::models::ManagedIdentityType,
        blob_service_uri: String,
        container_name: String,
    ) -> ManagedIdentityAzureBlobBackupStorageDescription {
        ManagedIdentityAzureBlobBackupStorageDescription {
            storage_kind,
            friendly_name: None,
            managed_identity_type,
            blob_service_uri,
            container_name,
        }
    }

    pub fn set_storage_kind(
        &mut self,
        storage_kind: ::models::BackupStorageKind,
    ) {
        self.storage_kind = storage_kind;
    }

    pub fn with_storage_kind(
        mut self,
        storage_kind: ::models::BackupStorageKind,
    ) -> ManagedIdentityAzureBlobBackupStorageDescription {
        self.storage_kind = storage_kind;
        self
    }

    pub fn storage_kind(&self) -> &::models::BackupStorageKind {
        &self.storage_kind
    }

    pub fn set_friendly_name(&mut self, friendly_name: String) {
        self.friendly_name = Some(friendly_name);
    }

    pub fn with_friendly_name(
        mut self,
        friendly_name: String,
    ) -> ManagedIdentityAzureBlobBackupStorageDescription {
        self.friendly_name = Some(friendly_name);
        self
    }

    pub fn friendly_name(&self) -> Option<&String> {
        self.friendly_name.as_ref()
    }

    pub fn reset_friendly_name(&mut self) {
        self.friendly_name = None;
    }

    pub fn set_managed_identity_type(
        &mut self,
        managed_identity_type: ::models::ManagedIdentityType,
    ) {
        self.managed_identity_type = managed_identity_type;
    }

    pub fn with_managed_identity_type(
        mut self,
        managed_identity_type: ::models::ManagedIdentityType,
    ) -> ManagedIdentityAzureBlobBackupStorageDescription {
        self.managed_identity_type = managed_identity_type;
        self
    }

    pub fn managed_identity_type(&self) -> &::models::ManagedIdentityType {
        &self.managed_identity_type
    }

    pub fn set_blob_service_uri(&mut self, blob_service_uri: String) {
        self.blob_service_uri = blob_service_uri;
    }

    pub fn with_blob_service_uri(
        mut self,
        blob_service_uri: String,
    ) -> ManagedIdentityAzureBlobBackupStorageDescription {
        self.blob_service_uri = blob_service_uri;
        self
    }

    pub fn blob_service_uri(&self) -> &String {
        &self.blob_service_uri
    }

    pub fn set_container_name(&mut self, container_name: String) {
        self.container_name = container_name;
    }

    pub fn with_container_name(
        mut self,
        container_name: String,
    ) -> ManagedIdentityAzureBlobBackupStorageDescription {
        self.container_name = container_name;
        self
    }

    pub fn container_name(&self) -> &String {
        &self.container_name
    }
}
