/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 7.1.0.45
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// NodeUpgradePhase : The state of the upgrading node.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NodeUpgradePhase {}

impl Default for NodeUpgradePhase {
    fn default() -> Self {
        Self::new()
    }
}

impl NodeUpgradePhase {
    /// The state of the upgrading node.
    pub fn new() -> NodeUpgradePhase {
        NodeUpgradePhase {}
    }
}

// TODO enum
// List of NodeUpgradePhase
//const (
//
//
//
//)
