/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PagedSubNameInfoList : A paged list of Service Fabric names. The list is paged when all of the results cannot fit in a single message. The next set of results can be obtained by executing the same query with the continuation token provided in this list.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PagedSubNameInfoList {
    /// The continuation token parameter is used to obtain next set of results. The continuation token is included in the response of the API when the results from the system do not fit in a single response. When this value is passed to the next API call, the API returns next set of results. If there are no further results, then the continuation token is not included in the response.
    #[serde(rename = "ContinuationToken")]
    continuation_token: Option<::models::ContinuationToken>,
    /// Indicates whether any name under the given name has been modified during the enumeration. If there was a modification, this property value is false.
    #[serde(rename = "IsConsistent")]
    is_consistent: Option<bool>,
    /// List of the child names.
    #[serde(rename = "SubNames")]
    sub_names: Option<Vec<::models::FabricName>>,
}

impl Default for PagedSubNameInfoList {
    fn default() -> Self {
        Self::new()
    }
}

impl PagedSubNameInfoList {
    /// A paged list of Service Fabric names. The list is paged when all of the results cannot fit in a single message. The next set of results can be obtained by executing the same query with the continuation token provided in this list.
    pub fn new() -> PagedSubNameInfoList {
        PagedSubNameInfoList {
            continuation_token: None,
            is_consistent: None,
            sub_names: None,
        }
    }

    pub fn set_continuation_token(
        &mut self,
        continuation_token: ::models::ContinuationToken,
    ) {
        self.continuation_token = Some(continuation_token);
    }

    pub fn with_continuation_token(
        mut self,
        continuation_token: ::models::ContinuationToken,
    ) -> PagedSubNameInfoList {
        self.continuation_token = Some(continuation_token);
        self
    }

    pub fn continuation_token(&self) -> Option<&::models::ContinuationToken> {
        self.continuation_token.as_ref()
    }

    pub fn reset_continuation_token(&mut self) {
        self.continuation_token = None;
    }

    pub fn set_is_consistent(&mut self, is_consistent: bool) {
        self.is_consistent = Some(is_consistent);
    }

    pub fn with_is_consistent(
        mut self,
        is_consistent: bool,
    ) -> PagedSubNameInfoList {
        self.is_consistent = Some(is_consistent);
        self
    }

    pub fn is_consistent(&self) -> Option<&bool> {
        self.is_consistent.as_ref()
    }

    pub fn reset_is_consistent(&mut self) {
        self.is_consistent = None;
    }

    pub fn set_sub_names(&mut self, sub_names: Vec<::models::FabricName>) {
        self.sub_names = Some(sub_names);
    }

    pub fn with_sub_names(
        mut self,
        sub_names: Vec<::models::FabricName>,
    ) -> PagedSubNameInfoList {
        self.sub_names = Some(sub_names);
        self
    }

    pub fn sub_names(&self) -> Option<&Vec<::models::FabricName>> {
        self.sub_names.as_ref()
    }

    pub fn reset_sub_names(&mut self) {
        self.sub_names = None;
    }
}
