/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ProbeExec : Exec command to run inside the container.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ProbeExec {
    /// Comma separated command to run inside the container for example \"sh, -c, echo hello world\".
    #[serde(rename = "command")]
    command: String,
}

impl ProbeExec {
    /// Exec command to run inside the container.
    pub fn new(command: String) -> ProbeExec {
        ProbeExec { command }
    }

    pub fn set_command(&mut self, command: String) {
        self.command = command;
    }

    pub fn with_command(mut self, command: String) -> ProbeExec {
        self.command = command;
        self
    }

    pub fn command(&self) -> &String {
        &self.command
    }
}
