/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 7.1.0.45
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PutPropertyBatchOperation : Puts the specified property under the specified name. Note that if one PropertyBatchOperation in a PropertyBatch fails, the entire batch fails and cannot be committed in a transactional manner.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PutPropertyBatchOperation {
    /// The kind of property batch operation, determined by the operation to be performed. The following are the possible values.
    #[serde(rename = "Kind")]
    kind: ::models::PropertyBatchOperationKind,
    /// The name of the Service Fabric property.
    #[serde(rename = "PropertyName")]
    property_name: ::models::PropertyName,
    /// Describes a Service Fabric property value.
    #[serde(rename = "Value")]
    value: ::models::PropertyValue,
    /// The property's custom type ID. Using this property, the user is able to tag the type of the value of the property.
    #[serde(rename = "CustomTypeId")]
    custom_type_id: Option<::models::PropertyCustomTypeId>,
}

impl PutPropertyBatchOperation {
    /// Puts the specified property under the specified name. Note that if one PropertyBatchOperation in a PropertyBatch fails, the entire batch fails and cannot be committed in a transactional manner.
    pub fn new(
        kind: ::models::PropertyBatchOperationKind,
        property_name: ::models::PropertyName,
        value: ::models::PropertyValue,
    ) -> PutPropertyBatchOperation {
        PutPropertyBatchOperation {
            kind,
            property_name,
            value,
            custom_type_id: None,
        }
    }

    pub fn set_kind(&mut self, kind: ::models::PropertyBatchOperationKind) {
        self.kind = kind;
    }

    pub fn with_kind(
        mut self,
        kind: ::models::PropertyBatchOperationKind,
    ) -> PutPropertyBatchOperation {
        self.kind = kind;
        self
    }

    pub fn kind(&self) -> &::models::PropertyBatchOperationKind {
        &self.kind
    }

    pub fn set_property_name(&mut self, property_name: ::models::PropertyName) {
        self.property_name = property_name;
    }

    pub fn with_property_name(
        mut self,
        property_name: ::models::PropertyName,
    ) -> PutPropertyBatchOperation {
        self.property_name = property_name;
        self
    }

    pub fn property_name(&self) -> &::models::PropertyName {
        &self.property_name
    }

    pub fn set_value(&mut self, value: ::models::PropertyValue) {
        self.value = value;
    }

    pub fn with_value(
        mut self,
        value: ::models::PropertyValue,
    ) -> PutPropertyBatchOperation {
        self.value = value;
        self
    }

    pub fn value(&self) -> &::models::PropertyValue {
        &self.value
    }

    pub fn set_custom_type_id(
        &mut self,
        custom_type_id: ::models::PropertyCustomTypeId,
    ) {
        self.custom_type_id = Some(custom_type_id);
    }

    pub fn with_custom_type_id(
        mut self,
        custom_type_id: ::models::PropertyCustomTypeId,
    ) -> PutPropertyBatchOperation {
        self.custom_type_id = Some(custom_type_id);
        self
    }

    pub fn custom_type_id(&self) -> Option<&::models::PropertyCustomTypeId> {
        self.custom_type_id.as_ref()
    }

    pub fn reset_custom_type_id(&mut self) {
        self.custom_type_id = None;
    }
}
