/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 6.4.0.36
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ScalingTriggerDescription : Describes the trigger for performing a scaling operation.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ScalingTriggerDescription {
    /// Specifies the kind of scaling trigger
    #[serde(rename = "Kind")]
    kind: ::models::ScalingTriggerKind,
}

impl ScalingTriggerDescription {
    /// Describes the trigger for performing a scaling operation.
    pub fn new(
        kind: ::models::ScalingTriggerKind,
    ) -> ScalingTriggerDescription {
        ScalingTriggerDescription { kind }
    }

    pub fn set_kind(&mut self, kind: ::models::ScalingTriggerKind) {
        self.kind = kind;
    }

    pub fn with_kind(
        mut self,
        kind: ::models::ScalingTriggerKind,
    ) -> ScalingTriggerDescription {
        self.kind = kind;
        self
    }

    pub fn kind(&self) -> &::models::ScalingTriggerKind {
        &self.kind
    }
}
