/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 6.3.0.9
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ServiceManifestName : The name of the service manifest.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ServiceManifestName {}

impl Default for ServiceManifestName {
    fn default() -> Self {
        Self::new()
    }
}

impl ServiceManifestName {
    /// The name of the service manifest.
    pub fn new() -> ServiceManifestName {
        ServiceManifestName {}
    }
}
