/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 6.5.0.36
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ServicePartitionKind : The kind of partitioning scheme used to partition the service.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ServicePartitionKind {}

impl Default for ServicePartitionKind {
    fn default() -> Self {
        Self::new()
    }
}

impl ServicePartitionKind {
    /// The kind of partitioning scheme used to partition the service.
    pub fn new() -> ServicePartitionKind {
        ServicePartitionKind {}
    }
}

// TODO enum
// List of ServicePartitionKind
//const (
//
//
//
//)
