/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// TargetApplicationName : The name of the target application, including the 'fabric:' URI scheme.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TargetApplicationName {}

impl Default for TargetApplicationName {
    fn default() -> Self {
        Self::new()
    }
}

impl TargetApplicationName {
    /// The name of the target application, including the 'fabric:' URI scheme.
    pub fn new() -> TargetApplicationName {
        TargetApplicationName {}
    }
}
