/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 7.0.0.42
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UpgradeDurationString : The estimated elapsed time spent processing the current overall upgrade.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UpgradeDurationString {}

impl Default for UpgradeDurationString {
    fn default() -> Self {
        Self::new()
    }
}

impl UpgradeDurationString {
    /// The estimated elapsed time spent processing the current overall upgrade.
    pub fn new() -> UpgradeDurationString {
        UpgradeDurationString {}
    }
}
