/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 6.4.0.36
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UpgradeType : The type of upgrade out of the following possible values.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UpgradeType {}

impl Default for UpgradeType {
    fn default() -> Self {
        Self::new()
    }
}

impl UpgradeType {
    /// The type of upgrade out of the following possible values.
    pub fn new() -> UpgradeType {
        UpgradeType {}
    }
}

// TODO enum
// List of UpgradeType
//const (
//
//
//
//)
