/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 7.0.0.42
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UpgradeDomainDurationString : The estimated elapsed time spent processing the current upgrade domain.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UpgradeDomainDurationString {}

impl Default for UpgradeDomainDurationString {
    fn default() -> Self {
        Self::new()
    }
}

impl UpgradeDomainDurationString {
    /// The estimated elapsed time spent processing the current upgrade domain.
    pub fn new() -> UpgradeDomainDurationString {
        UpgradeDomainDurationString {}
    }
}
