/*
 * Service Fabric Client APIs
 *
 * Service Fabric REST Client APIs allows management of Service Fabric clusters, applications and services.
 *
 * OpenAPI spec version: 8.2
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UpgradeUnitInfoList : List of upgrade units and their statuses.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UpgradeUnitInfoList {}

impl Default for UpgradeUnitInfoList {
    fn default() -> Self {
        Self::new()
    }
}

impl UpgradeUnitInfoList {
    /// List of upgrade units and their statuses.
    pub fn new() -> UpgradeUnitInfoList {
        UpgradeUnitInfoList {}
    }
}
